### ISSUE TITLE
fioreq: Specify keosd wallet name on the command line

### ISSUE THREAD

**Issue by lukestokes** [blockpane/fio-tools#1]
I see the -wallet param but I was wondering if I could pass in a keosd wallet name. I like to keep keys in different wallet names for different projects and it seems it assumes default.

**Comment by blockpane** [comment]
Yes, it's possible, use the `-n` flag. Give me a shout if it doesn't work, the keosd client (https://github.com/blockpane/fio-extras) isn't very heavily tested.

**Comment by lukestokes** [comment]
Works great! Sorry I didn't see it. :)
